services:
  mvc-blog:
    build: .
    container_name: php-app
    ports:
      - "9999:9999"
    volumes:
      - .:/var/www/html
    depends_on:
      - mvc-db
    networks:
      - mvc-network

  mvc-db:
    image: mysql
    container_name: mvc-db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: blog_daily
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mvc-network

  mvc-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mvc-db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mvc-network

networks:
  mvc-network:

volumes:
  mysql-data:
