services:
  mvc-blog:
    build: .
    container_name: php-app
    ports:
      - "9999:9999"
    volumes:
      - .:/var/www/html
    depends_on:
      - mvc-db
    networks:
      - mvc-network

  mvc-db:
    image: mysql
    container_name: mvc-db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: blog_daily
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mvc-network

  mvc-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mvc-db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    networks:
      - mvc-network

  mvc-jenkins:
    image: jenkins/jenkins:latest
    container_name: mvc-jenkins
    restart: on-failure 
    volumes:
      - jenkins-data:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000" 
    networks:
      - mvc-network

networks:
  mvc-network:

volumes:
  mysql-data:
  jenkins_home:
  jenkins-data:
