services:
  mvc-blog:
    build: .
    container_name: php-app
    ports:
      - "9999:9999"
    volumes:
      - .:/var/www/html
    depends_on:
      - mvc-db

  mvc-db:
    image: mysql
    container_name: mvc-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: blog_daily
    volumes:
      - mysql-data:/var/lib/mysql

  mvc-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mvc-db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: ""

  mvc-jenkins:
    image: devsainar/php-mvc-blog:1.0
    # image: docker-jenkins-blueocean:2.452.1-1
    container_name: mvc-jenkins
    restart: on-failure
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: "1"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - "8080:8080"
      - "50000:50000" 
    networks:
      - jenkins

networks:
  jenkins:

volumes:
  mysql-data:
  jenkins_home:
  jenkins-data:
  jenkins-docker-certs:
